let dados = [
    {
        titulo: "Edgar Allan Poe - Vol.1 - Darkside",
        capa: "assets/EdgarAllanPoe1.jpg",
        descricao: "Primeiro volume da coletânea de contos do escritor Edgar Allan Poe organizada e publicada pela editora Darkside separado em 2 volumes",
        status: "Lido",
        ano: "2024",
        avaliacao: "5",
        tags: "terror horror volume 1 vol darkside clássico classico lido 2024",
    },
    {
        titulo: "Edgar Allan Poe - Vol.2 - Darkside",
        capa: "assets/EdgarAllanPoe2.jpg",
        descricao: "Segundo volume da coletânea de contos do escritor Edgar Allan Poe organizada e publicada pela editora Darkside separado em 2 volumes",
        status: "Lido",
        ano: "2024",
        avaliacao: "5",
        tags: "terror horror volume 2 vol darkside clássico classico lido 2024",
    },
    {
        titulo: "Drácula",
        capa: "assets/DraculaDarkSideDarkEdition.webp",
        descricao: "Clássico do terror que tornou concreto a imagem do vampiro a qual conhecemos hoje.",
        status: "Lido",
        ano: "2024",
        avaliacao: "5",
        tags: "terror darkside clássico classico lido 2024",
    },
    {
        titulo: "O Retrato de Dorian Grey",
        capa: "assets/ORetratoDeDorianGrayDarkSide.jpg",
        descricao: "Livro o qual foi utiizado como prova contra seu autor e que no fim, o condenou a morte",
        status: "Lido",
        ano: "2024",
        avaliacao: "5",
        tags: "terror darkside clássico classico lido 2024",
    },
    {
        titulo: "O Fantasma da Ópera",
        capa: "assets/FantasmaDaOperaPrincipis.jpg",
        descricao: "Clássico da literatura gótica, um livro muito bom :)",
        status: "Lido",
        ano: "2024",
        avaliacao: "5",
        tags: "terror darkside clássico classico lido 2024",
    },
    {
        titulo: "Frankeinstein",
        capa: "assets/FrankeinsteinDarksideDeluxe.webp",
        descricao: "Lixo",
        status: "Lido",
        ano: "2024",
        avaliacao: "5",
        tags: "terror darkside clássico classico abandonado 2024",
    },
];